require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Cleaners::ApprovalProcessesController do

  # This should return the minimal set of attributes required to create a valid
  # Cleaners::ApprovalProcess. As you add validations to Cleaners::ApprovalProcess, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "approval_status" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Cleaners::ApprovalProcessesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all cleaners_approval_processes as @cleaners_approval_processes" do
      approval_process = Cleaners::ApprovalProcess.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cleaners_approval_processes).should eq([approval_process])
    end
  end

  describe "GET show" do
    it "assigns the requested cleaners_approval_process as @cleaners_approval_process" do
      approval_process = Cleaners::ApprovalProcess.create! valid_attributes
      get :show, {:id => approval_process.to_param}, valid_session
      assigns(:cleaners_approval_process).should eq(approval_process)
    end
  end

  describe "GET new" do
    it "assigns a new cleaners_approval_process as @cleaners_approval_process" do
      get :new, {}, valid_session
      assigns(:cleaners_approval_process).should be_a_new(Cleaners::ApprovalProcess)
    end
  end

  describe "GET edit" do
    it "assigns the requested cleaners_approval_process as @cleaners_approval_process" do
      approval_process = Cleaners::ApprovalProcess.create! valid_attributes
      get :edit, {:id => approval_process.to_param}, valid_session
      assigns(:cleaners_approval_process).should eq(approval_process)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cleaners::ApprovalProcess" do
        expect {
          post :create, {:cleaners_approval_process => valid_attributes}, valid_session
        }.to change(Cleaners::ApprovalProcess, :count).by(1)
      end

      it "assigns a newly created cleaners_approval_process as @cleaners_approval_process" do
        post :create, {:cleaners_approval_process => valid_attributes}, valid_session
        assigns(:cleaners_approval_process).should be_a(Cleaners::ApprovalProcess)
        assigns(:cleaners_approval_process).should be_persisted
      end

      it "redirects to the created cleaners_approval_process" do
        post :create, {:cleaners_approval_process => valid_attributes}, valid_session
        response.should redirect_to(Cleaners::ApprovalProcess.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cleaners_approval_process as @cleaners_approval_process" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cleaners::ApprovalProcess.any_instance.stub(:save).and_return(false)
        post :create, {:cleaners_approval_process => { "approval_status" => "invalid value" }}, valid_session
        assigns(:cleaners_approval_process).should be_a_new(Cleaners::ApprovalProcess)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cleaners::ApprovalProcess.any_instance.stub(:save).and_return(false)
        post :create, {:cleaners_approval_process => { "approval_status" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cleaners_approval_process" do
        approval_process = Cleaners::ApprovalProcess.create! valid_attributes
        # Assuming there are no other cleaners_approval_processes in the database, this
        # specifies that the Cleaners::ApprovalProcess created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cleaners::ApprovalProcess.any_instance.should_receive(:update).with({ "approval_status" => "MyString" })
        put :update, {:id => approval_process.to_param, :cleaners_approval_process => { "approval_status" => "MyString" }}, valid_session
      end

      it "assigns the requested cleaners_approval_process as @cleaners_approval_process" do
        approval_process = Cleaners::ApprovalProcess.create! valid_attributes
        put :update, {:id => approval_process.to_param, :cleaners_approval_process => valid_attributes}, valid_session
        assigns(:cleaners_approval_process).should eq(approval_process)
      end

      it "redirects to the cleaners_approval_process" do
        approval_process = Cleaners::ApprovalProcess.create! valid_attributes
        put :update, {:id => approval_process.to_param, :cleaners_approval_process => valid_attributes}, valid_session
        response.should redirect_to(approval_process)
      end
    end

    describe "with invalid params" do
      it "assigns the cleaners_approval_process as @cleaners_approval_process" do
        approval_process = Cleaners::ApprovalProcess.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cleaners::ApprovalProcess.any_instance.stub(:save).and_return(false)
        put :update, {:id => approval_process.to_param, :cleaners_approval_process => { "approval_status" => "invalid value" }}, valid_session
        assigns(:cleaners_approval_process).should eq(approval_process)
      end

      it "re-renders the 'edit' template" do
        approval_process = Cleaners::ApprovalProcess.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cleaners::ApprovalProcess.any_instance.stub(:save).and_return(false)
        put :update, {:id => approval_process.to_param, :cleaners_approval_process => { "approval_status" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cleaners_approval_process" do
      approval_process = Cleaners::ApprovalProcess.create! valid_attributes
      expect {
        delete :destroy, {:id => approval_process.to_param}, valid_session
      }.to change(Cleaners::ApprovalProcess, :count).by(-1)
    end

    it "redirects to the cleaners_approval_processes list" do
      approval_process = Cleaners::ApprovalProcess.create! valid_attributes
      delete :destroy, {:id => approval_process.to_param}, valid_session
      response.should redirect_to(cleaners_approval_processes_url)
    end
  end

end
