require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Cleaners::PreferencesController do

  # This should return the minimal set of attributes required to create a valid
  # Cleaners::Preference. As you add validations to Cleaners::Preference, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "preferred_time" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Cleaners::PreferencesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all cleaners_preferences as @cleaners_preferences" do
      preference = Cleaners::Preference.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cleaners_preferences).should eq([preference])
    end
  end

  describe "GET show" do
    it "assigns the requested cleaners_preference as @cleaners_preference" do
      preference = Cleaners::Preference.create! valid_attributes
      get :show, {:id => preference.to_param}, valid_session
      assigns(:cleaners_preference).should eq(preference)
    end
  end

  describe "GET new" do
    it "assigns a new cleaners_preference as @cleaners_preference" do
      get :new, {}, valid_session
      assigns(:cleaners_preference).should be_a_new(Cleaners::Preference)
    end
  end

  describe "GET edit" do
    it "assigns the requested cleaners_preference as @cleaners_preference" do
      preference = Cleaners::Preference.create! valid_attributes
      get :edit, {:id => preference.to_param}, valid_session
      assigns(:cleaners_preference).should eq(preference)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cleaners::Preference" do
        expect {
          post :create, {:cleaners_preference => valid_attributes}, valid_session
        }.to change(Cleaners::Preference, :count).by(1)
      end

      it "assigns a newly created cleaners_preference as @cleaners_preference" do
        post :create, {:cleaners_preference => valid_attributes}, valid_session
        assigns(:cleaners_preference).should be_a(Cleaners::Preference)
        assigns(:cleaners_preference).should be_persisted
      end

      it "redirects to the created cleaners_preference" do
        post :create, {:cleaners_preference => valid_attributes}, valid_session
        response.should redirect_to(Cleaners::Preference.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cleaners_preference as @cleaners_preference" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cleaners::Preference.any_instance.stub(:save).and_return(false)
        post :create, {:cleaners_preference => { "preferred_time" => "invalid value" }}, valid_session
        assigns(:cleaners_preference).should be_a_new(Cleaners::Preference)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cleaners::Preference.any_instance.stub(:save).and_return(false)
        post :create, {:cleaners_preference => { "preferred_time" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cleaners_preference" do
        preference = Cleaners::Preference.create! valid_attributes
        # Assuming there are no other cleaners_preferences in the database, this
        # specifies that the Cleaners::Preference created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cleaners::Preference.any_instance.should_receive(:update).with({ "preferred_time" => "MyString" })
        put :update, {:id => preference.to_param, :cleaners_preference => { "preferred_time" => "MyString" }}, valid_session
      end

      it "assigns the requested cleaners_preference as @cleaners_preference" do
        preference = Cleaners::Preference.create! valid_attributes
        put :update, {:id => preference.to_param, :cleaners_preference => valid_attributes}, valid_session
        assigns(:cleaners_preference).should eq(preference)
      end

      it "redirects to the cleaners_preference" do
        preference = Cleaners::Preference.create! valid_attributes
        put :update, {:id => preference.to_param, :cleaners_preference => valid_attributes}, valid_session
        response.should redirect_to(preference)
      end
    end

    describe "with invalid params" do
      it "assigns the cleaners_preference as @cleaners_preference" do
        preference = Cleaners::Preference.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cleaners::Preference.any_instance.stub(:save).and_return(false)
        put :update, {:id => preference.to_param, :cleaners_preference => { "preferred_time" => "invalid value" }}, valid_session
        assigns(:cleaners_preference).should eq(preference)
      end

      it "re-renders the 'edit' template" do
        preference = Cleaners::Preference.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cleaners::Preference.any_instance.stub(:save).and_return(false)
        put :update, {:id => preference.to_param, :cleaners_preference => { "preferred_time" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cleaners_preference" do
      preference = Cleaners::Preference.create! valid_attributes
      expect {
        delete :destroy, {:id => preference.to_param}, valid_session
      }.to change(Cleaners::Preference, :count).by(-1)
    end

    it "redirects to the cleaners_preferences list" do
      preference = Cleaners::Preference.create! valid_attributes
      delete :destroy, {:id => preference.to_param}, valid_session
      response.should redirect_to(cleaners_preferences_url)
    end
  end

end
